### ISSUE TITLE
Pretrained Checkpoints

### ISSUE THREAD

**Issue by hemingkx** [Victorwz/VaLM#4]
Hi! Thanks for your awesome work!

I wonder if there are any trained checkpoints released for VaLM? Thank you!

**Comment by Victorwz** [comment]
Hi heming, 
Thanks for your interest in our work and sorry for the late response due to NeurIPS ddl. The copyright of the pre-trained checkpoints belongs to Microsoft Research. I have checkout from that but I will try my best to contact for the potential release of the pre-trained models. If I cannot get permission, I will find time to reproduce the models and maybe plan to release them in July?

Weizhi

**Comment by hemingkx** [comment]
Thanks for your response and looking forward to the released checkpoints. Good luck in NIPS submission!

**Comment by guyyariv** [comment]
Hi, could you please provide the checkpoints?
